.TH "src/push_swap/memory/1_0_mem_alloc.c" 3 "Fri Mar 21 2025 18:12:07" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/push_swap/memory/1_0_mem_alloc.c
.SH SYNOPSIS
.br
.PP
\fC#include 'push_swap\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdata_alloc_vars\fP (int argc, char **argv, t_list_program *list_program)"
.br
.ti -1c
.RI "void \fBdata_alloc_1\fP (t_list_program *list_program)"
.br
.ti -1c
.RI "void \fBdata_alloc_2\fP (t_list_program *list_program)"
.br
.ti -1c
.RI "void \fBdata_alloc\fP (int argc, char **argv, t_list_program *list_program)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void data_alloc (int argc, char ** argv, t_list_program * list_program)"

.SS "void data_alloc_1 (t_list_program * list_program)"

.SS "void data_alloc_2 (t_list_program * list_program)"

.SS "void data_alloc_vars (int argc, char ** argv, t_list_program * list_program)"

.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
