.TH "src/push_swap/memory/1_1_mem_clear.c" 3 "Thu Mar 20 2025 16:03:10" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/push_swap/memory/1_1_mem_clear.c
.SH SYNOPSIS
.br
.PP
\fC#include 'push_swap\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBft_free_push_swap_end\fP (t_list_program *list_program)"
.br
.ti -1c
.RI "void \fBft_free_push_swap_halt\fP (t_list_program *list_program)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void ft_free_push_swap_end (t_list_program * list_program)"

.SS "void ft_free_push_swap_halt (t_list_program * list_program)"

.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
