.TH "src/push_swap/tracers/1_2_debugger_helpers.c" 3 "Fri Mar 21 2025 18:12:08" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/push_swap/tracers/1_2_debugger_helpers.c
.SH SYNOPSIS
.br
.PP
\fC#include 'push_swap\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsort_stack_dbg\fP (t_list_program *list_program)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void sort_stack_dbg (t_list_program * list_program)"

.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
