.TH "src/checker_bonus/libs/mylibs/mylibc/src/src_all/1b_ft_open.c" 3 "Thu Mar 20 2025 16:01:00" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/checker_bonus/libs/mylibs/mylibc/src/src_all/1b_ft_open.c
.SH SYNOPSIS
.br
.PP
\fC#include 'mylibc\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_open_readorwrite\fP (char *file, int read_or_write)"
.br
.RI "0 = read, 1 = write, 2 = append "
.ti -1c
.RI "int \fBft_open\fP (char *file, int flags,\&.\&.\&.)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int ft_open (char * file, int flags,  \&.\&.\&.)"

.SS "int ft_open_readorwrite (char * file, int read_or_write)"

.PP
0 = read, 1 = write, 2 = append 
.PP
\fBParameters\fP
.RS 4
\fIfile\fP file to open 
.br
\fIread_or_write\fP 0 = read, 1 = write, 2 = append 
.RE
.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
