.TH "src/checker_bonus/libs/mylibs/mylibc/src/src_all/1c_1_ft_memcmp.c" 3 "Thu Mar 20 2025 16:01:01" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/checker_bonus/libs/mylibs/mylibc/src/src_all/1c_1_ft_memcmp.c
.SH SYNOPSIS
.br
.PP
\fC#include 'mylibc\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_strncmp\fP (const char *s1, const char *s2, size_t n)"
.br
.ti -1c
.RI "int \fBft_strcmp\fP (const char *s1, const char *s2)"
.br
.ti -1c
.RI "int \fBft_strcmp_duplicate\fP (char *str, char **array)"
.br
.ti -1c
.RI "int \fBft_strcmp_duplicate_inter\fP (char **array)"
.br
.ti -1c
.RI "int \fBft_memcmp\fP (const void *s1, const void *s2, size_t n)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int ft_memcmp (const void * s1, const void * s2, size_t n)"

.SS "int ft_strcmp (const char * s1, const char * s2)"

.SS "int ft_strcmp_duplicate (char * str, char ** array)"

.SS "int ft_strcmp_duplicate_inter (char ** array)"

.SS "int ft_strncmp (const char * s1, const char * s2, size_t n)"

.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
