.TH "src/checker_bonus/libs/mylibs/mylibc/src/src_all/1c_ft_itoa.c" 3 "Thu Mar 20 2025 16:01:01" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/checker_bonus/libs/mylibs/mylibc/src/src_all/1c_ft_itoa.c
.SH SYNOPSIS
.br
.PP
\fC#include 'mylibc\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBdigits_to_bits\fP (int digits)"
.br
.ti -1c
.RI "int \fBft_digit_count\fP (long int i)"
.br
.ti -1c
.RI "long int \fBft_abs_comp\fP (long int nb, char *str)"
.br
.ti -1c
.RI "char * \fBft_itoa\fP (int n)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int digits_to_bits (int digits)"

.SS "long int ft_abs_comp (long int nb, char * str)"

.SS "int ft_digit_count (long int i)"

.SS "char * ft_itoa (int n)"

.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
