.TH "src/checker_bonus/libs/mylibs/mylibc/src/src_all/1e_ft_putstr1.c" 3 "Thu Mar 20 2025 16:01:01" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/checker_bonus/libs/mylibs/mylibc/src/src_all/1e_ft_putstr1.c
.SH SYNOPSIS
.br
.PP
\fC#include 'mylibc\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_putstr\fP (char *str)"
.br
.ti -1c
.RI "int \fBft_putstr_str\fP (char **str)"
.br
.ti -1c
.RI "void \fBft_putstr_fd\fP (char *str, int fd)"
.br
.ti -1c
.RI "int \fBft_putstr_fd_fpr\fP (long fd, char *s)"
.br
.ti -1c
.RI "int \fBft_putstrstr_fd_fpr\fP (long fd, char **str)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int ft_putstr (char * str)"

.SS "void ft_putstr_fd (char * str, int fd)"

.SS "int ft_putstr_fd_fpr (long fd, char * s)"

.SS "int ft_putstr_str (char ** str)"

.SS "int ft_putstrstr_fd_fpr (long fd, char ** str)"

.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
