.TH "src/push_swap/sort/presorting/3_1_presorting_getmin.c" 3 "Fri Mar 21 2025 18:12:08" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/push_swap/sort/presorting/3_1_presorting_getmin.c
.SH SYNOPSIS
.br
.PP
\fC#include 'push_swap\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "t_list_dls * \fBget_next_min\fP (t_list_dls **stack)"
.br
.ti -1c
.RI "void \fBadd_index_numbers\fP (t_list_dls *list)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void add_index_numbers (t_list_dls * list)"

.SS "t_list_dls * get_next_min (t_list_dls ** stack)"

.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
