.TH "src/push_swap/sort/selection/3_2_selectionsort.c" 3 "Fri Mar 21 2025 18:12:08" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/push_swap/sort/selection/3_2_selectionsort.c
.SH SYNOPSIS
.br
.PP
\fC#include 'push_swap\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBselection_sort\fP (t_list_program *list_program)"
.br
.ti -1c
.RI "void \fBselection_sort_recursion\fP (int *pushes, t_list_program *list_program)"
.br
.ti -1c
.RI "void \fBsort_3\fP (t_list_dls **stack_a, t_list_program *list_program)"
.br
.ti -1c
.RI "void \fBselection_sort_merge_back\fP (int *pushes, t_list_program *list_program)"
.br
.ti -1c
.RI "int \fBmin_node_pos\fP (t_list_program *list_program)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int min_node_pos (t_list_program * list_program)"

.SS "void selection_sort (t_list_program * list_program)"

.SS "void selection_sort_merge_back (int * pushes, t_list_program * list_program)"

.SS "void selection_sort_recursion (int * pushes, t_list_program * list_program)"

.SS "void sort_3 (t_list_dls ** stack_a, t_list_program * list_program)"

.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
