.TH "src/checker_bonus/libs/mylibs/mylibc/src/src_all/3_3_ft_toupper.c" 3 "Thu Mar 20 2025 16:01:02" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/checker_bonus/libs/mylibs/mylibc/src/src_all/3_3_ft_toupper.c
.SH SYNOPSIS
.br
.PP
\fC#include 'mylibc\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_toupper\fP (int c)"
.br
.ti -1c
.RI "int \fBft_tolower\fP (int c)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int ft_tolower (int c)"

.SS "int ft_toupper (int c)"

.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
