.TH "src/push_swap/sort/quicksort/3_4_sort3_chunk.c" 3 "Thu Mar 20 2025 16:03:10" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/push_swap/sort/quicksort/3_4_sort3_chunk.c
.SH SYNOPSIS
.br
.PP
\fC#include 'push_swap\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsort_3_chunk_case\fP (t_sort_3_cases case_, t_list_program *list_program)"
.br
.ti -1c
.RI "void \fBsort_3_chunk_case_1\fP (t_sort_3_cases case_, t_list_program *list_program)"
.br
.ti -1c
.RI "void \fBsort_3_chunk\fP (t_list_program *list_program)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void sort_3_chunk (t_list_program * list_program)"

.SS "void sort_3_chunk_case (t_sort_3_cases case_, t_list_program * list_program)"

.SS "void sort_3_chunk_case_1 (t_sort_3_cases case_, t_list_program * list_program)"

.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
