.TH "src/push_swap/sort/gear/3_5_quicksort_partial.c" 3 "Thu Mar 20 2025 16:03:10" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/push_swap/sort/gear/3_5_quicksort_partial.c
.SH SYNOPSIS
.br
.PP
\fC#include 'push_swap\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBpivot_calculation_partial\fP (t_chunk *chunk_to_sort, t_splits *split_chunks)"
.br
.ti -1c
.RI "void \fBrecursive_split_chunk_partial\fP (t_chunk *chunk_to_sort, t_list_program *list_program)"
.br
.ti -1c
.RI "void \fBquick_sort_partial\fP (t_list_program *list_program)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void pivot_calculation_partial (t_chunk * chunk_to_sort, t_splits * split_chunks)"

.SS "void quick_sort_partial (t_list_program * list_program)"

.SS "void recursive_split_chunk_partial (t_chunk * chunk_to_sort, t_list_program * list_program)"

.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
