.TH "src/push_swap/sort/optim/3_7_moves_optim.c" 3 "Fri Mar 21 2025 18:12:08" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/push_swap/sort/optim/3_7_moves_optim.c
.SH SYNOPSIS
.br
.PP
\fC#include 'push_swap\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmoves_optimizations_0\fP (int *j, t_list_program *list_program)"
.br
.ti -1c
.RI "void \fBmoves_optimizations_1\fP (int *j, t_list_program *list_program)"
.br
.ti -1c
.RI "void \fBft_strlcpy_optm\fP (int *j, char *move, int *i, t_list_program *list_program)"
.br
.ti -1c
.RI "void \fBmoves_optimizations\fP (t_list_program *list_program)"
.br
.ti -1c
.RI "void \fBmoves_optimizations_2\fP (int *j, t_list_program *list_program)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void ft_strlcpy_optm (int * j, char * move, int * i, t_list_program * list_program)"

.SS "void moves_optimizations (t_list_program * list_program)"

.SS "void moves_optimizations_0 (int * j, t_list_program * list_program)"

.SS "void moves_optimizations_1 (int * j, t_list_program * list_program)"

.SS "void moves_optimizations_2 (int * j, t_list_program * list_program)"

.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
