.TH "src/checker_bonus/libs/mylibs/mylibc/src/src_all/3_ft_prime.c" 3 "Thu Mar 20 2025 16:01:02" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/checker_bonus/libs/mylibs/mylibc/src/src_all/3_ft_prime.c
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBis_prime_recursive\fP (int nb, int i)"
.br
.ti -1c
.RI "int \fBft_is_prime\fP (int nb)"
.br
.ti -1c
.RI "int \fBft_find_next_prime\fP (int nb)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int ft_find_next_prime (int nb)"

.SS "int ft_is_prime (int nb)"

.SS "int is_prime_recursive (int nb, int i)"

.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
