.TH "src/checker_bonus/libs/mylibs/mylibc/src/src_all/3_probability.c" 3 "Thu Mar 20 2025 16:01:02" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/checker_bonus/libs/mylibs/mylibc/src/src_all/3_probability.c
.SH SYNOPSIS
.br
.PP
\fC#include 'mylibc\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "long \fBft_factorial\fP (long nb)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "long ft_factorial (long nb)"

.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
