.TH "src/push_swap/moves/4_1_moves_both.c" 3 "Thu Mar 20 2025 16:03:10" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/push_swap/moves/4_1_moves_both.c
.SH SYNOPSIS
.br
.PP
\fC#include 'push_swap\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBswap_both\fP (t_list_program *list_program)"
.br
.ti -1c
.RI "void \fBrotate_both\fP (char *direction, t_list_program *list_program)"
.br
.ti -1c
.RI "void \fBmove_stack_fromto_case\fP (char *move_case, t_list_program *list_program)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void move_stack_fromto_case (char * move_case, t_list_program * list_program)"

.SS "void rotate_both (char * direction, t_list_program * list_program)"

.SS "void swap_both (t_list_program * list_program)"

.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
