.TH "src/push_swap/moves/4_2_moves_fromto.c" 3 "Fri Mar 21 2025 18:12:07" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/push_swap/moves/4_2_moves_fromto.c
.SH SYNOPSIS
.br
.PP
\fC#include 'push_swap\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmove_stack_fromto1\fP (t_position from, t_position to, t_list_program *list_program)"
.br
.ti -1c
.RI "void \fBmove_stack_fromto2\fP (t_position from, t_position to, t_list_program *list_program)"
.br
.ti -1c
.RI "void \fBmove_stack_fromto\fP (t_position from, t_position to, t_list_program *list_program)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void move_stack_fromto (t_position from, t_position to, t_list_program * list_program)"

.SS "void move_stack_fromto1 (t_position from, t_position to, t_list_program * list_program)"

.SS "void move_stack_fromto2 (t_position from, t_position to, t_list_program * list_program)"

.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
