.TH "src/checker_bonus/libs/mylibs/mylibc/inc/_algo.h" 3 "Thu Mar 20 2025 16:00:59" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/checker_bonus/libs/mylibs/mylibc/inc/_algo.h
.SH SYNOPSIS
.br
.PP
\fC#include <unistd\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBheapify\fP (int arr[], int n, int i)"
.br
.ti -1c
.RI "void \fBheap_sort\fP (int arr[], int n)"
.br
.ti -1c
.RI "void \fBquick_sort\fP (int arr[], int low, int high, int depthlimit)"
.br
.ti -1c
.RI "int \fBft_log_introsort\fP (int n)"
.br
.ti -1c
.RI "void \fBintro_sort\fP (int arr[], int n)"
.br
.ti -1c
.RI "void \fBswap_introsort\fP (int *a, int *b)"
.br
.ti -1c
.RI "int \fBpartition\fP (int arr[], int low, int high)"
.br
.ti -1c
.RI "int \fBft_abs\fP (int number)"
.br
.ti -1c
.RI "void \fBmatrix3_init\fP (float(*matrix)[3])"
.br
.ti -1c
.RI "void \fBprint_bits\fP (unsigned char octet)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int ft_abs (int number)"

.SS "int ft_log_introsort (int n)"

.SS "void heap_sort (int arr[], int n)"

.SS "void heapify (int arr[], int n, int i)"

.SS "void intro_sort (int arr[], int n)"

.SS "void matrix3_init (float(*) matrix[3])"

.SS "int partition (int arr[], int low, int high)"

.SS "void print_bits (unsigned char octet)"

.SS "void quick_sort (int arr[], int low, int high, int depthlimit)"

.SS "void swap_introsort (int * a, int * b)"

.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
