.TH "src/checker_bonus/libs/mylibs/mylibc/src/1b_input Directory Reference" 3 "Thu Mar 20 2025 16:01:03" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/checker_bonus/libs/mylibs/mylibc/src/1b_input Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fB0_open_close\fP"
.br
.ti -1c
.RI "directory \fB1_ft_fgets_heap\fP"
.br
.ti -1c
.RI "directory \fB2_ft_sed\fP"
.br
.ti -1c
.RI "directory \fB3_ft_sscanf_heap\fP"
.br
.in -1c
