.TH "src/checker_bonus/libs/mylibs/mylibc/src/1b_input/2_ft_sed Directory Reference" 3 "Thu Mar 20 2025 16:01:03" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/checker_bonus/libs/mylibs/mylibc/src/1b_input/2_ft_sed Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB1b_ft_sed\&.c\fP"
.br
.in -1c
