.TH "src/checker_bonus/libs/mylibs/mylibc/src/1a_memory/0_alloc_clear Directory Reference" 3 "Thu Mar 20 2025 16:01:03" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/checker_bonus/libs/mylibs/mylibc/src/1a_memory/0_alloc_clear Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB1a_ft_calloc\&.c\fP"
.br
.ti -1c
.RI "file \fB1a_ft_calloc_fd\&.c\fP"
.br
.ti -1c
.RI "file \fB1a_ft_free\&.c\fP"
.br
.in -1c
