.TH "src/checker_bonus/libs/mylibs/mylibc/src/1a_memory Directory Reference" 3 "Thu Mar 20 2025 16:01:03" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/checker_bonus/libs/mylibs/mylibc/src/1a_memory Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fB0_alloc_clear\fP"
.br
.ti -1c
.RI "directory \fB1_exit_halt_assert\fP"
.br
.ti -1c
.RI "directory \fB2_garbage_collector\fP"
.br
.in -1c
