.TH "src/checker_bonus/libs/mylibs/mylibc/src/1c_string_manip Directory Reference" 3 "Thu Mar 20 2025 16:01:03" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/checker_bonus/libs/mylibs/mylibc/src/1c_string_manip Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fB0_copy_set\fP"
.br
.ti -1c
.RI "directory \fB1_tokenize_cat\fP"
.br
.ti -1c
.RI "directory \fB2_search_cmp\fP"
.br
.ti -1c
.RI "directory \fB3_converters_math\fP"
.br
.ti -1c
.RI "directory \fB4_data_is\fP"
.br
.ti -1c
.RI "directory \fB5_algos_others\fP"
.br
.in -1c
