.TH "src/checker_bonus/libs/mylibs/mylibc/src/4__data_parser/1_readers Directory Reference" 3 "Thu Mar 20 2025 16:01:03" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/checker_bonus/libs/mylibs/mylibc/src/4__data_parser/1_readers Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB4_ft_sscanf\&.c\fP"
.br
.in -1c
