.TH "src/push_swap/tracers Directory Reference" 3 "Fri Mar 21 2025 18:12:08" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/push_swap/tracers Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB1_2_debugger_helpers\&.c\fP"
.br
.ti -1c
.RI "file \fB1_2_printers_tracers\&.c\fP"
.br
.in -1c
