.TH "src/checker_bonus/libs/mylibs/mylibc/inc/mylibc_defines.h" 3 "Thu Mar 20 2025 16:01:00" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/checker_bonus/libs/mylibs/mylibc/inc/mylibc_defines.h
.SH SYNOPSIS
.br
.PP
\fC#include 'mylibc\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAX_ALLOCATIONS\fP   10240"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MAX_ALLOCATIONS   10240"

.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
