.TH "inc/push_swap_defines.h" 3 "Thu Mar 20 2025 16:00:59" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/push_swap_defines.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDBG\fP   0"
.br
.ti -1c
.RI "#define \fBNAME_M\fP   'log/2\&.Memory_Check/allocs/malloc_allocs\&.txt'"
.br
.ti -1c
.RI "#define \fBMAX_MOVES\fP   10000"
.br
.ti -1c
.RI "#define \fBSA_PATH\fP   'log/3\&.Unit_Testing/stack_a\&.txt'"
.br
.ti -1c
.RI "#define \fBSB_PATH\fP   'log/3\&.Unit_Testing/stack_b\&.txt'"
.br
.ti -1c
.RI "#define \fBPRICES_PATH\fP   'log/3\&.Unit_Testing/prices\&.txt'"
.br
.ti -1c
.RI "#define \fBDBG_PATH\fP   'log/3\&.Unit_Testing/dbging\&.txt'"
.br
.ti -1c
.RI "#define \fBALGO\fP   0"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ALGO   0"

.SS "#define DBG   0"

.SS "#define DBG_PATH   'log/3\&.Unit_Testing/dbging\&.txt'"

.SS "#define MAX_MOVES   10000"

.SS "#define NAME_M   'log/2\&.Memory_Check/allocs/malloc_allocs\&.txt'"

.SS "#define PRICES_PATH   'log/3\&.Unit_Testing/prices\&.txt'"

.SS "#define SA_PATH   'log/3\&.Unit_Testing/stack_a\&.txt'"

.SS "#define SB_PATH   'log/3\&.Unit_Testing/stack_b\&.txt'"

.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
