.TH "inc/push_swap_data.h" 3 "Thu Mar 20 2025 16:00:59" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/push_swap_data.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdbool\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBs_list_program\fP"
.br
.ti -1c
.RI "struct \fBs_chunk\fP"
.br
.ti -1c
.RI "struct \fBs_splits\fP"
.br
.ti -1c
.RI "struct \fBs_node_pos_locator\fP"
.br
.ti -1c
.RI "struct \fBs_move_lower_cost\fP"
.br
.ti -1c
.RI "struct \fBs_sort_gearing\fP"
.br
.ti -1c
.RI "struct \fBs_x\fP"
.br
.ti -1c
.RI "struct \fBs_chunk1\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAX_ALLOCATIONS\fP   10000"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBs_list_dls\fP \fBt_list_dls\fP"
.br
.ti -1c
.RI "typedef struct \fBs_list_garbage\fP \fBt_list_garbage\fP"
.br
.ti -1c
.RI "typedef struct \fBs_list_program\fP \fBt_list_program\fP"
.br
.ti -1c
.RI "typedef enum \fBe_position\fP \fBt_position\fP"
.br
.ti -1c
.RI "typedef enum \fBe_sort_3_cases\fP \fBt_sort_3_cases\fP"
.br
.ti -1c
.RI "typedef struct \fBs_chunk\fP \fBt_chunk\fP"
.br
.ti -1c
.RI "typedef struct \fBs_splits\fP \fBt_splits\fP"
.br
.ti -1c
.RI "typedef struct \fBs_node_pos_locator\fP \fBt_node_pos_locator\fP"
.br
.ti -1c
.RI "typedef struct \fBs_move_lower_cost\fP \fBt_move_lower_cost\fP"
.br
.ti -1c
.RI "typedef struct \fBs_sort_gearing\fP \fBt_sort_gearing\fP"
.br
.ti -1c
.RI "typedef struct \fBs_x\fP \fBt_x\fP"
.br
.ti -1c
.RI "typedef struct \fBs_chunk1\fP \fBt_chunk1\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBe_position\fP { \fBBOTTOM_B\fP, \fBTOP_B\fP, \fBBOTTOM_A\fP, \fBTOP_A\fP }"
.br
.ti -1c
.RI "enum \fBe_sort_3_cases\fP { \fBCASE_0\fP, \fBCASE_A\fP, \fBCASE_B\fP, \fBCASE_C\fP, \fBCASE_D\fP, \fBCASE_E\fP, \fBCASE_F\fP }"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MAX_ALLOCATIONS   10000"

.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBs_chunk\fP \fBt_chunk\fP"

.SS "typedef struct \fBs_chunk1\fP \fBt_chunk1\fP"

.SS "typedef struct \fBs_list_dls\fP \fBt_list_dls\fP"

.SS "typedef struct \fBs_list_garbage\fP \fBt_list_garbage\fP"

.SS "typedef struct \fBs_list_program\fP \fBt_list_program\fP"

.SS "typedef struct \fBs_move_lower_cost\fP \fBt_move_lower_cost\fP"

.SS "typedef struct \fBs_node_pos_locator\fP \fBt_node_pos_locator\fP"

.SS "typedef enum \fBe_position\fP \fBt_position\fP"

.SS "typedef enum \fBe_sort_3_cases\fP \fBt_sort_3_cases\fP"

.SS "typedef struct \fBs_sort_gearing\fP \fBt_sort_gearing\fP"

.SS "typedef struct \fBs_splits\fP \fBt_splits\fP"

.SS "typedef struct \fBs_x\fP \fBt_x\fP"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBe_position\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIBOTTOM_B \fP\fP
.TP
\fB\fITOP_B \fP\fP
.TP
\fB\fIBOTTOM_A \fP\fP
.TP
\fB\fITOP_A \fP\fP
.SS "enum \fBe_sort_3_cases\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fICASE_0 \fP\fP
.TP
\fB\fICASE_A \fP\fP
.TP
\fB\fICASE_B \fP\fP
.TP
\fB\fICASE_C \fP\fP
.TP
\fB\fICASE_D \fP\fP
.TP
\fB\fICASE_E \fP\fP
.TP
\fB\fICASE_F \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
