.TH "s_bresenham" 3 "Thu Mar 20 2025 16:01:03" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_bresenham
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mylibc_data\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBx0\fP"
.br
.ti -1c
.RI "int \fBy0\fP"
.br
.ti -1c
.RI "int \fBx1\fP"
.br
.ti -1c
.RI "int \fBy1\fP"
.br
.ti -1c
.RI "int \fBdx\fP"
.br
.ti -1c
.RI "int \fBdy\fP"
.br
.ti -1c
.RI "int \fBsx\fP"
.br
.ti -1c
.RI "int \fBsy\fP"
.br
.ti -1c
.RI "int \fBerr\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int dx"

.SS "int dy"

.SS "int err"

.SS "int sx"

.SS "int sy"

.SS "int x0"

.SS "int x1"

.SS "int y0"

.SS "int y1"


.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
