.TH "s_list_dls" 3 "Thu Mar 20 2025 16:01:03" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_list_dls
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mylibc_data\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBvalue\fP"
.br
.ti -1c
.RI "\fBint\fP \fBindex\fP"
.br
.ti -1c
.RI "\fBstruct\fP \fBs_list_dls\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBstruct\fP \fBs_list_dls\fP * \fBprev\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBint\fP index"

.SS "\fBstruct\fP \fBs_list_dls\fP* next"

.SS "\fBstruct\fP \fBs_list_dls\fP* prev"

.SS "int value"


.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
