.TH "s_list_garbage" 3 "Thu Mar 20 2025 16:01:03" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_list_garbage
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mylibc_data\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBallocated_pointers\fP [\fBMAX_ALLOCATIONS\fP]"
.br
.ti -1c
.RI "int \fBblocks_count\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "void* allocated_pointers[\fBMAX_ALLOCATIONS\fP]"

.SS "int blocks_count"


.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
