.TH "s_list_s" 3 "Thu Mar 20 2025 16:01:03" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_list_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mylibc_data\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBcontent\fP"
.br
.ti -1c
.RI "struct \fBs_list_s\fP * \fBnext\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "void* content"

.SS "struct \fBs_list_s\fP* next"


.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
