.TH "s_list_program" 3 "Thu Mar 20 2025 16:01:03" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_list_program
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <push_swap_data\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBdbg\fP"
.br
.ti -1c
.RI "\fBt_list_garbage\fP * \fBlist_garbage\fP"
.br
.ti -1c
.RI "int \fBargc\fP"
.br
.ti -1c
.RI "char ** \fBargv\fP"
.br
.ti -1c
.RI "char ** \fBstack_a_array\fP"
.br
.ti -1c
.RI "int \fBstack_a_size\fP"
.br
.ti -1c
.RI "\fBt_list_dls\fP ** \fBstack_a\fP"
.br
.ti -1c
.RI "\fBt_list_dls\fP ** \fBstack_b\fP"
.br
.ti -1c
.RI "char ** \fBmoves\fP"
.br
.ti -1c
.RI "int \fBmax_moves\fP"
.br
.ti -1c
.RI "int \fBmove_count\fP"
.br
.ti -1c
.RI "char ** \fBmoves_optim\fP"
.br
.ti -1c
.RI "int \fBmove_optim_count\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int argc"

.SS "char** argv"

.SS "int dbg"

.SS "\fBt_list_garbage\fP* list_garbage"

.SS "int max_moves"

.SS "int move_count"

.SS "int move_optim_count"

.SS "char** moves"

.SS "char** moves_optim"

.SS "\fBt_list_dls\fP** stack_a"

.SS "char** stack_a_array"

.SS "int stack_a_size"

.SS "\fBt_list_dls\fP** stack_b"


.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
