.TH "s_sort_gearing" 3 "Thu Mar 20 2025 16:01:03" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_sort_gearing
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <push_swap_data\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBrotations_a\fP"
.br
.ti -1c
.RI "int \fBrotations_a_abs\fP"
.br
.ti -1c
.RI "\fBt_move_lower_cost\fP * \fBt_move_lower_cost\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int rotations_a"

.SS "int rotations_a_abs"

.SS "\fBt_move_lower_cost\fP* \fBt_move_lower_cost\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
