.TH "src/push_swap/memory/1_1_mem_clear.c" 3 "Sun Mar 16 2025 16:17:05" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/push_swap/memory/1_1_mem_clear.c
.SH SYNOPSIS
.br
.PP
\fC#include 'push_swap\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBft_free_push_swap_end\fP (\fBt_list_program\fP *list_program)"
.br
.ti -1c
.RI "void \fBft_free_push_swap_halt\fP (\fBt_list_program\fP *list_program)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void ft_free_push_swap_end (\fBt_list_program\fP * list_program)"

.SS "void ft_free_push_swap_halt (\fBt_list_program\fP * list_program)"

.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
