.TH "src/push_swap/tracers/1_2_printers_tracers.c" 3 "Sun Mar 16 2025 16:17:05" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/push_swap/tracers/1_2_printers_tracers.c
.SH SYNOPSIS
.br
.PP
\fC#include 'push_swap\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBprint_results\fP (\fBt_list_program\fP *list_program)"
.br
.ti -1c
.RI "void \fBft_printers\fP (\fBt_ft_printers_db\fP s, \fBt_list_program\fP *list_program)"
.br
.ti -1c
.RI "void \fBft_printers_gearsort\fP (\fBt_ft_printers_db\fP s, \fBt_move_lower_cost\fP *v, \fBt_list_program\fP *list_program)"
.br
.ti -1c
.RI "void \fBprinter_dbg_split\fP (\fBt_ft_printers_db\fP s, \fBt_splits\fP *split_chunks, \fBt_list_program\fP *list_program)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void ft_printers (\fBt_ft_printers_db\fP s, \fBt_list_program\fP * list_program)"

.SS "void ft_printers_gearsort (\fBt_ft_printers_db\fP s, \fBt_move_lower_cost\fP * v, \fBt_list_program\fP * list_program)"

.SS "void print_results (\fBt_list_program\fP * list_program)"

.SS "void printer_dbg_split (\fBt_ft_printers_db\fP s, \fBt_splits\fP * split_chunks, \fBt_list_program\fP * list_program)"

.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
