.TH "src/push_swap/tracers/1_2_printers_tracers.c" 3 "Thu Mar 20 2025 16:03:10" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/push_swap/tracers/1_2_printers_tracers.c
.SH SYNOPSIS
.br
.PP
\fC#include 'push_swap\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBprint_results\fP (t_list_program *list_program)"
.br
.ti -1c
.RI "void \fBft_printers\fP (t_ft_printers_db s, t_list_program *list_program)"
.br
.ti -1c
.RI "void \fBft_printers_gearsort\fP (t_ft_printers_db s, t_move_lower_cost *v, t_list_program *list_program)"
.br
.ti -1c
.RI "void \fBprinter_dbg_split\fP (t_ft_printers_db s, t_splits *split_chunks, t_list_program *list_program)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void ft_printers (t_ft_printers_db s, t_list_program * list_program)"

.SS "void ft_printers_gearsort (t_ft_printers_db s, t_move_lower_cost * v, t_list_program * list_program)"

.SS "void print_results (t_list_program * list_program)"

.SS "void printer_dbg_split (t_ft_printers_db s, t_splits * split_chunks, t_list_program * list_program)"

.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
