.TH "src/checker_bonus/libs/mylibs/mylibc/src/src_all/1c_1_ft_memchr1.c" 3 "Thu Mar 20 2025 16:01:00" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/checker_bonus/libs/mylibs/mylibc/src/src_all/1c_1_ft_memchr1.c
.SH SYNOPSIS
.br
.PP
\fC#include 'mylibc\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBft_strchr\fP (const char *s, int c)"
.br
.ti -1c
.RI "int \fBft_strchr_char_duplicate\fP (char c, char **argv, int i)"
.br
.ti -1c
.RI "int * \fBft_strchr_int_duplicate\fP (int *array_int, int size, int position)"
.br
.ti -1c
.RI "char * \fBft_strchr_gnl\fP (char *s, int c)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char * ft_strchr (const char * s, int c)"

.SS "int ft_strchr_char_duplicate (char c, char ** argv, int i)"

.SS "char * ft_strchr_gnl (char * s, int c)"

.SS "int * ft_strchr_int_duplicate (int * array_int, int size, int position)"

.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
