.TH "src/checker_bonus/libs/mylibs/mylibc/src/src_all/1c_1_ft_memchr.c" 3 "Thu Mar 20 2025 16:01:00" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/checker_bonus/libs/mylibs/mylibc/src/src_all/1c_1_ft_memchr.c
.SH SYNOPSIS
.br
.PP
\fC#include 'mylibc\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_contains\fP (int num, char **argv, int i)"
.br
.ti -1c
.RI "char * \fBft_strnstr\fP (const char *haystack, const char *needle, size_t len)"
.br
.ti -1c
.RI "char * \fBft_strrchr\fP (const char *s, int c)"
.br
.ti -1c
.RI "void * \fBft_memmem\fP (const void *haystack, size_t haystacklen, const void *needle, size_t needlelen)"
.br
.ti -1c
.RI "void * \fBft_memchr\fP (const void *s, int c, size_t n)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int ft_contains (int num, char ** argv, int i)"

.SS "void * ft_memchr (const void * s, int c, size_t n)"

.SS "void * ft_memmem (const void * haystack, size_t haystacklen, const void * needle, size_t needlelen)"

.SS "char * ft_strnstr (const char * haystack, const char * needle, size_t len)"

.SS "char * ft_strrchr (const char * s, int c)"

.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
