.TH "src/checker_bonus/libs/mylibs/mylibc/src/src_all/1c_ft_strlen.c" 3 "Thu Mar 20 2025 16:01:01" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/checker_bonus/libs/mylibs/mylibc/src/src_all/1c_ft_strlen.c
.SH SYNOPSIS
.br
.PP
\fC#include 'mylibc\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "size_t \fBft_strlen\fP (const char *s)"
.br
.ti -1c
.RI "int \fBft_array_size\fP (char **s)"
.br
.ti -1c
.RI "size_t \fBft_strlen_gnl\fP (char *s, int c)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int ft_array_size (char ** s)"

.SS "size_t ft_strlen (const char * s)"

.SS "size_t ft_strlen_gnl (char * s, int c)"

.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
