.TH "src/checker_bonus/libs/mylibs/mylibc/src/src_all/1c_ft_isalnumascii.c" 3 "Thu Mar 20 2025 16:01:01" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/checker_bonus/libs/mylibs/mylibc/src/src_all/1c_ft_isalnumascii.c
.SH SYNOPSIS
.br
.PP
\fC#include 'mylibc\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_isalnum\fP (int c)"
.br
.ti -1c
.RI "int \fBft_isprint\fP (int c)"
.br
.ti -1c
.RI "int \fBft_isascii\fP (int c)"
.br
.ti -1c
.RI "int \fBft_isalpha\fP (int c)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int ft_isalnum (int c)"

.SS "int ft_isalpha (int c)"

.SS "int ft_isascii (int c)"

.SS "int ft_isprint (int c)"

.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
