.TH "src/checker_bonus/libs/mylibs/mylibc/src/src_all/1d_ft_strtok_split.c" 3 "Thu Mar 20 2025 16:01:01" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/checker_bonus/libs/mylibs/mylibc/src/src_all/1d_ft_strtok_split.c
.SH SYNOPSIS
.br
.PP
\fC#include 'mylibc\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "long * \fBft_split_long\fP (char *filename, char const *array_source, char delimitator, int *size)"
.br
.ti -1c
.RI "char ** \fBft_split\fP (char *filename, char const *s, char c)"
.br
.ti -1c
.RI "int \fBft_countwords\fP (char const *s, char c)"
.br
.ti -1c
.RI "char * \fBft_strtrim\fP (char const *s1, char const *set)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int ft_countwords (char const * s, char c)"

.SS "char ** ft_split (char * filename, char const * s, char c)"

.SS "long * ft_split_long (char * filename, char const * array_source, char delimitator, int * size)"

.SS "char * ft_strtrim (char const * s1, char const * set)"

.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
