.TH "src/checker_bonus/libs/mylibs/mylibc/src/src_all/2_0_ft_slinked_list1.c" 3 "Thu Mar 20 2025 16:01:02" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/checker_bonus/libs/mylibs/mylibc/src/src_all/2_0_ft_slinked_list1.c
.SH SYNOPSIS
.br
.PP
\fC#include 'mylibc\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBft_free_ls_simple\fP (\fBt_list_s\fP *stack)"
.br
.ti -1c
.RI "\fBt_list_s\fP * \fBft_lstlast_s\fP (\fBt_list_s\fP *lst)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void ft_free_ls_simple (\fBt_list_s\fP * stack)"

.SS "\fBt_list_s\fP * ft_lstlast_s (\fBt_list_s\fP * lst)"

.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
