.TH "src/push_swap/sort/selection/3_2_selectionsort.c" 3 "Sun Mar 16 2025 16:17:05" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/push_swap/sort/selection/3_2_selectionsort.c
.SH SYNOPSIS
.br
.PP
\fC#include 'push_swap\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBselection_sort\fP (\fBt_list_program\fP *list_program)"
.br
.ti -1c
.RI "void \fBselection_sort_recursion\fP (int *pushes, \fBt_list_program\fP *list_program)"
.br
.ti -1c
.RI "void \fBsort_3\fP (\fBt_list_dls\fP **stack_a, \fBt_list_program\fP *list_program)"
.br
.ti -1c
.RI "void \fBselection_sort_merge_back\fP (int *pushes, \fBt_list_program\fP *list_program)"
.br
.ti -1c
.RI "int \fBmin_node_pos\fP (\fBt_list_program\fP *list_program)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int min_node_pos (\fBt_list_program\fP * list_program)"

.SS "void selection_sort (\fBt_list_program\fP * list_program)"

.SS "void selection_sort_merge_back (int * pushes, \fBt_list_program\fP * list_program)"

.SS "void selection_sort_recursion (int * pushes, \fBt_list_program\fP * list_program)"

.SS "void sort_3 (\fBt_list_dls\fP ** stack_a, \fBt_list_program\fP * list_program)"

.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
