.TH "src/push_swap/sort/quicksort/3_4_sort3_chunk.c" 3 "Sun Mar 16 2025 16:17:05" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/push_swap/sort/quicksort/3_4_sort3_chunk.c
.SH SYNOPSIS
.br
.PP
\fC#include 'push_swap\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsort_3_chunk_case\fP (\fBt_sort_3_cases\fP case_, \fBt_list_program\fP *list_program)"
.br
.ti -1c
.RI "void \fBsort_3_chunk_case_1\fP (\fBt_sort_3_cases\fP case_, \fBt_list_program\fP *list_program)"
.br
.ti -1c
.RI "void \fBsort_3_chunk\fP (\fBt_list_program\fP *list_program)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void sort_3_chunk (\fBt_list_program\fP * list_program)"

.SS "void sort_3_chunk_case (\fBt_sort_3_cases\fP case_, \fBt_list_program\fP * list_program)"

.SS "void sort_3_chunk_case_1 (\fBt_sort_3_cases\fP case_, \fBt_list_program\fP * list_program)"

.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
