.TH "src/push_swap/sort/quicksort/3_4_quicksort.c" 3 "Sun Mar 16 2025 16:17:05" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/push_swap/sort/quicksort/3_4_quicksort.c
.SH SYNOPSIS
.br
.PP
\fC#include 'push_swap\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBquick_sort_pushswap\fP (\fBt_list_program\fP *list_program)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void quick_sort_pushswap (\fBt_list_program\fP * list_program)"

.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
