.TH "src/push_swap/sort/gear/3_5_gearsort_pricing2.c" 3 "Sun Mar 16 2025 16:17:05" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/push_swap/sort/gear/3_5_gearsort_pricing2.c
.SH SYNOPSIS
.br
.PP
\fC#include 'push_swap\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBnode_pos_locator_is_in_place\fP (char stack_from, int value, \fBt_node_pos_locator\fP *v)"
.br
.ti -1c
.RI "void \fBhigh_up_stack\fP (\fBt_list_program\fP *list_program)"
.br
.ti -1c
.RI "void \fBlow_up_stack\fP (\fBt_list_program\fP *list_program)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void high_up_stack (\fBt_list_program\fP * list_program)"

.SS "void low_up_stack (\fBt_list_program\fP * list_program)"

.SS "int node_pos_locator_is_in_place (char stack_from, int value, \fBt_node_pos_locator\fP * v)"

.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
