.TH "src/push_swap/sort/gear/3_5_quicksort_partial.c" 3 "Sun Mar 16 2025 16:17:05" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/push_swap/sort/gear/3_5_quicksort_partial.c
.SH SYNOPSIS
.br
.PP
\fC#include 'push_swap\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBpivot_calculation_partial\fP (\fBt_chunk\fP *chunk_to_sort, \fBt_splits\fP *split_chunks)"
.br
.ti -1c
.RI "void \fBrecursive_split_chunk_partial\fP (\fBt_chunk\fP *chunk_to_sort, \fBt_list_program\fP *list_program)"
.br
.ti -1c
.RI "void \fBquick_sort_partial\fP (\fBt_list_program\fP *list_program)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void pivot_calculation_partial (\fBt_chunk\fP * chunk_to_sort, \fBt_splits\fP * split_chunks)"

.SS "void quick_sort_partial (\fBt_list_program\fP * list_program)"

.SS "void recursive_split_chunk_partial (\fBt_chunk\fP * chunk_to_sort, \fBt_list_program\fP * list_program)"

.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
