.TH "src/push_swap/sort/gear/3_5_gearsort_pricing.c" 3 "Sun Mar 16 2025 16:17:05" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/push_swap/sort/gear/3_5_gearsort_pricing.c
.SH SYNOPSIS
.br
.PP
\fC#include 'push_swap\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBgear_sort_pushswap\fP (\fBt_list_program\fP *list_program)"
.br
.ti -1c
.RI "void \fBsort_gearing\fP (char stack_from, char stack_to, int base_case, \fBt_list_program\fP *list_program)"
.br
.ti -1c
.RI "void \fBsort_move_lower_cost\fP (char stack_from, \fBt_move_lower_cost\fP *v, \fBt_list_program\fP *list_program)"
.br
.ti -1c
.RI "int \fBnode_pos_locator\fP (int value, \fBt_list_program\fP *list_program, char type, char stack_from)"
.br
.ti -1c
.RI "int \fBsort_gearing_is_base_case\fP (int base_case, \fBt_list_program\fP *list_program)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void gear_sort_pushswap (\fBt_list_program\fP * list_program)"

.SS "int node_pos_locator (int value, \fBt_list_program\fP * list_program, char type, char stack_from)"

.SS "void sort_gearing (char stack_from, char stack_to, int base_case, \fBt_list_program\fP * list_program)"

.SS "int sort_gearing_is_base_case (int base_case, \fBt_list_program\fP * list_program)"

.SS "void sort_move_lower_cost (char stack_from, \fBt_move_lower_cost\fP * v, \fBt_list_program\fP * list_program)"

.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
