.TH "src/checker_bonus/libs/mylibs/mylibc/src/src_all/3_bitwise.c" 3 "Thu Mar 20 2025 16:01:02" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/checker_bonus/libs/mylibs/mylibc/src/src_all/3_bitwise.c
.SH SYNOPSIS
.br
.PP
\fC#include 'mylibc\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBprint_bits\fP (unsigned char octet)"
.br
.ti -1c
.RI "unsigned char \fBreverse_bits\fP (unsigned char octet)"
.br
.ti -1c
.RI "unsigned char \fBswap_bits\fP (unsigned char octet)"
.br
.ti -1c
.RI "unsigned int \fBgray_code\fP (unsigned int n)"
.br
.ti -1c
.RI "void \fBgenerate_gray_codes\fP (unsigned int limit)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void generate_gray_codes (unsigned int limit)"

.SS "unsigned int gray_code (unsigned int n)"

.SS "void print_bits (unsigned char octet)"

.SS "unsigned char reverse_bits (unsigned char octet)"

.SS "unsigned char swap_bits (unsigned char octet)"

.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
