.TH "src/checker_bonus/libs/mylibs/mylibc/src/src_all/3_ft_fibonacci.c" 3 "Thu Mar 20 2025 16:01:02" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/checker_bonus/libs/mylibs/mylibc/src/src_all/3_ft_fibonacci.c
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_fibonacci\fP (int index)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int ft_fibonacci (int index)"

.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
