.TH "src/checker_bonus/libs/mylibs/mylibc/src/src_all/3_raster_scan_bresenham.c" 3 "Thu Mar 20 2025 16:01:02" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/checker_bonus/libs/mylibs/mylibc/src/src_all/3_raster_scan_bresenham.c
.SH SYNOPSIS
.br
.PP
\fC#include 'mylibc\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBbresenham_line\fP (\fBt_bresenham\fP *b, void(*put_pixel)(int, int))"
.br
.ti -1c
.RI "void \fBexample_put_pixel\fP (int x, int y)"
.br
.ti -1c
.RI "void \fBbresenham_step\fP (\fBt_bresenham\fP *b)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void bresenham_line (\fBt_bresenham\fP * b, void(*)(int, int) put_pixel)"

.SS "void bresenham_step (\fBt_bresenham\fP * b)"

.SS "void example_put_pixel (int x, int y)"

.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
