.TH "src/push_swap/sort/gear Directory Reference" 3 "Sun Mar 16 2025 16:17:05" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/push_swap/sort/gear Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB3_5_gearsort_pricing\&.c\fP"
.br
.ti -1c
.RI "file \fB3_5_gearsort_pricing2\&.c\fP"
.br
.ti -1c
.RI "file \fB3_5_quicksort_partial\&.c\fP"
.br
.in -1c
