.TH "src/push_swap/memory Directory Reference" 3 "Sun Mar 16 2025 16:17:05" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/push_swap/memory Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB1_0_mem_alloc\&.c\fP"
.br
.ti -1c
.RI "file \fB1_1_mem_clear\&.c\fP"
.br
.in -1c
