.TH "src/push_swap/sort Directory Reference" 3 "Sun Mar 16 2025 16:17:05" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/push_swap/sort Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBgear\fP"
.br
.ti -1c
.RI "directory \fBoptim\fP"
.br
.ti -1c
.RI "directory \fBpresorting\fP"
.br
.ti -1c
.RI "directory \fBquicksort\fP"
.br
.ti -1c
.RI "directory \fBradix\fP"
.br
.ti -1c
.RI "directory \fBselection\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB3_0_sort_stack\&.c\fP"
.br
.RI "Implements the main sorting logic for the push_swap program\&. "
.in -1c
