.TH "src/src_all Directory Reference" 3 "Thu Mar 20 2025 16:02:12" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/src_all Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB1_0_mem_alloc\&.c\fP"
.br
.ti -1c
.RI "file \fB1_1_mem_clear\&.c\fP"
.br
.ti -1c
.RI "file \fB1_2_debugger_helpers\&.c\fP"
.br
.ti -1c
.RI "file \fB1_2_printers_tracers\&.c\fP"
.br
.ti -1c
.RI "file \fB2_0_input_check\&.c\fP"
.br
.ti -1c
.RI "file \fB3_0_sort_stack\&.c\fP"
.br
.RI "Implements the main sorting logic for the push_swap program\&. "
.ti -1c
.RI "file \fB3_1_introsort_presort\&.c\fP"
.br
.ti -1c
.RI "file \fB3_1_presorting_getmin\&.c\fP"
.br
.ti -1c
.RI "file \fB3_2_selectionsort\&.c\fP"
.br
.ti -1c
.RI "file \fB3_3_radixsort\&.c\fP"
.br
.ti -1c
.RI "file \fB3_4_quicksort\&.c\fP"
.br
.ti -1c
.RI "file \fB3_4_sort3_chunk\&.c\fP"
.br
.ti -1c
.RI "file \fB3_5_gearsort_pricing\&.c\fP"
.br
.ti -1c
.RI "file \fB3_5_gearsort_pricing2\&.c\fP"
.br
.ti -1c
.RI "file \fB3_5_quicksort_partial\&.c\fP"
.br
.ti -1c
.RI "file \fB3_7_moves_optim\&.c\fP"
.br
.ti -1c
.RI "file \fB4_0_moves_direction\&.c\fP"
.br
.ti -1c
.RI "file \fB4_1_moves_both\&.c\fP"
.br
.ti -1c
.RI "file \fB4_2_moves_fromto\&.c\fP"
.br
.ti -1c
.RI "file \fBchecker_bonus\&.c\fP"
.br
.ti -1c
.RI "file \fBpush_swap\&.c\fP"
.br
.in -1c
