.TH "src/checker_bonus/libs/mylibs/mylibc/src/4__data_parser Directory Reference" 3 "Thu Mar 20 2025 16:01:03" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/checker_bonus/libs/mylibs/mylibc/src/4__data_parser Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fB0_memory\fP"
.br
.ti -1c
.RI "directory \fB1_readers\fP"
.br
.ti -1c
.RI "directory \fB2_trimmers\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB4_ft_data_parser\&.c\fP"
.br
.in -1c
