.TH "src/checker_bonus/libs/mylibs/mylibc/src/1c_string_manip/3_converters_math Directory Reference" 3 "Thu Mar 20 2025 16:01:03" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/checker_bonus/libs/mylibs/mylibc/src/1c_string_manip/3_converters_math Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB1c_ft_atoi\&.c\fP"
.br
.ti -1c
.RI "file \fB1c_ft_atoi_base\&.c\fP"
.br
.ti -1c
.RI "file \fB1c_ft_itoa\&.c\fP"
.br
.ti -1c
.RI "file \fB1c_ft_math\&.c\fP"
.br
.in -1c
