.TH "src/checker_bonus/libs/mylibs/mylibc/src/3_algos_others/2_strings_algos Directory Reference" 3 "Thu Mar 20 2025 16:01:03" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/checker_bonus/libs/mylibs/mylibc/src/3_algos_others/2_strings_algos Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB3_1_fizzbuzz\&.c\fP"
.br
.ti -1c
.RI "file \fB3_2_union\&.c\fP"
.br
.ti -1c
.RI "file \fB3_2_wdmatch\&.c\fP"
.br
.ti -1c
.RI "file \fB3_3_expand_str\&.c\fP"
.br
.ti -1c
.RI "file \fB3_3_ft_toupper\&.c\fP"
.br
.ti -1c
.RI "file \fB3_4_rev_wstr\&.c\fP"
.br
.ti -1c
.RI "file \fB3_4_rostring\&.c\fP"
.br
.in -1c
