.TH "inc Directory Reference" 3 "Thu Mar 20 2025 16:01:04" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBpush_swap\&.h\fP"
.br
.ti -1c
.RI "file \fBpush_swap_data\&.h\fP"
.br
.ti -1c
.RI "file \fBpush_swap_defines\&.h\fP"
.br
.in -1c
