.TH "s_chunk" 3 "Sun Mar 16 2025 16:17:05" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_chunk
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <push_swap_data\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBmin\fP"
.br
.ti -1c
.RI "int \fBmax\fP"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.ti -1c
.RI "\fBt_position\fP \fBposition\fP"
.br
.ti -1c
.RI "int \fBsize_parent\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int max"

.SS "int min"

.SS "\fBt_position\fP position"

.SS "int size"

.SS "int size_parent"


.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
