.TH "s_chunk1" 3 "Sun Mar 16 2025 16:17:05" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_chunk1
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <push_swap_data\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBmin\fP"
.br
.ti -1c
.RI "int \fBmax\fP"
.br
.ti -1c
.RI "int \fBpivot1\fP"
.br
.ti -1c
.RI "int \fBpivot2\fP"
.br
.ti -1c
.RI "struct \fBs_chunk1\fP * \fBsplit_chunks_max\fP"
.br
.ti -1c
.RI "struct \fBs_chunk1\fP * \fBsplit_chunks_mid\fP"
.br
.ti -1c
.RI "struct \fBs_chunk1\fP * \fBsplit_chunks_min\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int max"

.SS "int min"

.SS "int pivot1"

.SS "int pivot2"

.SS "struct \fBs_chunk1\fP* split_chunks_max"

.SS "struct \fBs_chunk1\fP* split_chunks_mid"

.SS "struct \fBs_chunk1\fP* split_chunks_min"


.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
