.TH "s_list_hashmap" 3 "Thu Mar 20 2025 16:01:03" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_list_hashmap
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mylibc_data\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBchar\fP * \fBkey\fP"
.br
.ti -1c
.RI "int \fBvalue\fP"
.br
.ti -1c
.RI "\fBstruct\fP \fBs_list_hashmap\fP * \fBnext\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBchar\fP* key"

.SS "\fBstruct\fP \fBs_list_hashmap\fP* next"

.SS "int value"


.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
