.TH "s_list_snprintf" 3 "Thu Mar 20 2025 16:01:03" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_list_snprintf
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mylibc_data\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBformat\fP"
.br
.ti -1c
.RI "va_list \fBargs\fP"
.br
.ti -1c
.RI "char * \fBstr_p\fP"
.br
.ti -1c
.RI "size_t \fBremaining\fP"
.br
.ti -1c
.RI "int \fBlen\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "va_list args"

.SS "const char* format"

.SS "int len"

.SS "size_t remaining"

.SS "char* str_p"


.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
