.TH "s_move_lower_cost" 3 "Sun Mar 16 2025 16:17:05" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_move_lower_cost
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <push_swap_data\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBt_list_dls\fP * \fBcurrent\fP"
.br
.ti -1c
.RI "int \fBcurrent_rotations\fP"
.br
.ti -1c
.RI "int \fBcurrent_price\fP"
.br
.ti -1c
.RI "int \fBprice_of_cheapest\fP"
.br
.ti -1c
.RI "int \fBmoves_to_cheapest\fP"
.br
.ti -1c
.RI "int \fBvalue_of_cheapest\fP"
.br
.ti -1c
.RI "int \fBmoves_to_cheapest_abs\fP"
.br
.ti -1c
.RI "int \fBrotations_b_cheapest\fP"
.br
.ti -1c
.RI "int \fBrotations_b\fP"
.br
.ti -1c
.RI "int \fBrotations_b_abs\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBt_list_dls\fP* current"

.SS "int current_price"

.SS "int current_rotations"

.SS "int moves_to_cheapest"

.SS "int moves_to_cheapest_abs"

.SS "int price_of_cheapest"

.SS "int rotations_b"

.SS "int rotations_b_abs"

.SS "int rotations_b_cheapest"

.SS "int value_of_cheapest"


.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
