.TH "s_node_pos_locator" 3 "Sun Mar 16 2025 16:17:05" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_node_pos_locator
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <push_swap_data\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBt_list_dls\fP * \fBcurrent\fP"
.br
.ti -1c
.RI "\fBt_list_dls\fP ** \fBstack_b\fP"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.ti -1c
.RI "int \fBpos\fP"
.br
.ti -1c
.RI "int \fBmax_node\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBt_list_dls\fP* current"

.SS "int max_node"

.SS "int pos"

.SS "int size"

.SS "\fBt_list_dls\fP** stack_b"


.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
