.TH "s_splits" 3 "Sun Mar 16 2025 16:17:05" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_splits
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <push_swap_data\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBmin_number\fP"
.br
.ti -1c
.RI "int \fBpivot1\fP"
.br
.ti -1c
.RI "int \fBpivot2\fP"
.br
.ti -1c
.RI "int \fBmax_number\fP"
.br
.ti -1c
.RI "int \fBsize_total\fP"
.br
.ti -1c
.RI "\fBt_position\fP \fBposition_from\fP"
.br
.ti -1c
.RI "\fBt_chunk\fP \fBmax\fP"
.br
.ti -1c
.RI "\fBt_chunk\fP \fBmid\fP"
.br
.ti -1c
.RI "\fBt_chunk\fP \fBmin\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBt_chunk\fP max"

.SS "int max_number"

.SS "\fBt_chunk\fP mid"

.SS "\fBt_chunk\fP min"

.SS "int min_number"

.SS "int pivot1"

.SS "int pivot2"

.SS "\fBt_position\fP position_from"

.SS "int size_total"


.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
