.TH "s_x" 3 "Thu Mar 20 2025 16:01:03" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_x
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <push_swap_data\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.ti -1c
.RI "int \fBi\fP"
.br
.ti -1c
.RI "int \fBj\fP"
.br
.ti -1c
.RI "int \fBk\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int i"

.SS "int j"

.SS "int k"

.SS "int x"

.SS "int y"


.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
