.TH "s_x" 3 "Sun Mar 16 2025 16:17:05" "push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_x
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <push_swap_data\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBint\fP \fBx\fP"
.br
.ti -1c
.RI "\fBint\fP \fBy\fP"
.br
.ti -1c
.RI "int \fBi\fP"
.br
.ti -1c
.RI "\fBint\fP \fBj\fP"
.br
.ti -1c
.RI "\fBint\fP \fBk\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int i"

.SS "\fBint\fP j"

.SS "\fBint\fP k"

.SS "\fBint\fP x"

.SS "\fBint\fP y"


.SH "Author"
.PP 
Generated automatically by Doxygen for push_swap from the source code\&.
